name: Build Containers

on:
  push:
    tags:
      - "v*"
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      service:
        description: Service to build
        required: true
        default: cernbox-web
      push:
        description: Push images to registries
        required: true
        type: boolean
        default: true
      extra_tag:
        description: Optional extra tag suffix
        required: false

jobs:
  build:
    runs-on: docker
    if: >-
      github.event_name == 'workflow_dispatch' ||
      startsWith(github.ref, 'refs/tags/v') ||
      contains(github.event.head_commit.message, 'dev-build') ||
      contains(github.event.head_commit.message, 'stage-build')

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (release only)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Nushell
        env:
          NU_VERSION: "0.98.0"
        run: |
          curl -fsSL -o /tmp/nu.tar.gz https://github.com/nushell/nushell/releases/download/${NU_VERSION}/nu-${NU_VERSION}-x86_64-unknown-linux-gnu.tar.gz
          mkdir -p /tmp/nu
          tar -xzf /tmp/nu.tar.gz -C /tmp/nu --strip-components=1
          sudo mv /tmp/nu/nu /usr/local/bin/nu
          nu --version

      - name: Compute build push flag
        id: flags
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "push=${{ inputs.push }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref }}" == refs/tags/v* ]]; then
            echo "push=true" >> $GITHUB_OUTPUT
          else
            echo "push=true" >> $GITHUB_OUTPUT
          fi

      - name: Build
        env:
          FORGEJO_REGISTRY_USER: ${{ secrets.FORGEJO_REGISTRY_USER }}
          FORGEJO_REGISTRY_TOKEN: ${{ secrets.FORGEJO_REGISTRY_TOKEN }}
        run: |
          nu scripts/build.nu --service ${{ inputs.service || 'cernbox-web' }} --push ${{ steps.flags.outputs.push }} --latest true --extra-tag "${{ inputs.extra_tag }}"
