# SPDX-License-Identifier: AGPL-3.0-or-later
# DockyPody: container build scripts and images
# Copyright (C) 2025 Mahdi Baghbani <mahdi-baghbani@azadehafzar.io>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Shared sshd lifecycle helpers for OCM-capable containers.
# Env vars: OCM_SSH_ENABLED, OCM_SSH_MODE, OCM_SSH_DEFAULT_USER,
#           OCM_SSH_PORT, OCM_SSH_LISTEN, OCM_SSH_PRIVATE_KEY,
#           OCM_SSH_KNOWN_HOSTS.

def generate-host-keys [] {
    let ssh_dir = "/etc/ssh"
    let host_key = $"($ssh_dir)/ssh_host_ed25519_key"

    if ($host_key | path exists) {
        print "[ocm-sshd] Host keys already exist"
        return
    }

    print "[ocm-sshd] Generating SSH host keys..."
    let r = (^ssh-keygen -A | complete)
    if $r.exit_code != 0 {
        error make {msg: $"[ocm-sshd] ssh-keygen -A failed exit=($r.exit_code): ($r.stderr | str trim)"}
    }
    print "[ocm-sshd] Host keys generated"
}

def setup-sshd-config [
    port: int,
    listen: string,
    user: string
] {
    let sshd_config = "/etc/ssh/sshd_config"
    let sshd_config_backup = $"($sshd_config).dockypody-original"
    if not ($sshd_config_backup | path exists) {
        if ($sshd_config | path exists) {
            cp $sshd_config $sshd_config_backup
        }
    }

    let config_content = $"# Auto-generated by ocm-sshd.nu
# Do not edit manually - changes will be overwritten on container restart

Port ($port)
ListenAddress ($listen)

# Authentication
PermitRootLogin yes
PubkeyAuthentication yes
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no

# Host keys
HostKey /etc/ssh/ssh_host_ed25519_key
HostKey /etc/ssh/ssh_host_rsa_key

# Security
X11Forwarding no
AllowTcpForwarding no
PermitTunnel no
GatewayPorts no
MaxAuthTries 3
LoginGraceTime 30
ClientAliveInterval 300
ClientAliveCountMax 2

# Logging
LogLevel INFO
SyslogFacility AUTH

# Allow only the configured user
AllowUsers ($user)

# Subsystem
Subsystem sftp /usr/lib/openssh/sftp-server
"

    $config_content | save -f $sshd_config
    print $"[ocm-sshd] Configured sshd_config port=($port) user=($user)"
}

def setup-authorized-keys [user: string] {
    let user_info = (try { ^getent passwd $user } catch { "" })
    let home_dir = if ($user_info | str trim | is-empty) {
        if $user == "root" { "/root" } else { $"/home/($user)" }
    } else {
        ($user_info | split row ":") | get 5
    }

    let ssh_dir = $"($home_dir)/.ssh"
    let authorized_keys = $"($ssh_dir)/authorized_keys"

    if not ($ssh_dir | path exists) {
        mkdir $ssh_dir
    }

    let default_pub_key = "/opt/dockypody/ssh/dockypody-dev-ed25519.pub"
    if ($default_pub_key | path exists) {
        let pub_key_content = (open --raw $default_pub_key)
        if not ($authorized_keys | path exists) {
            $pub_key_content | save -f $authorized_keys
            print $"[ocm-sshd] Created authorized_keys for ($user)"
        } else {
            let current_keys = (open --raw $authorized_keys)
            if not ($current_keys | str contains $pub_key_content) {
                $"\n($pub_key_content)" | save --append $authorized_keys
                print $"[ocm-sshd] Appended default key to authorized_keys for ($user)"
            } else {
                print $"[ocm-sshd] Default key already in authorized_keys for ($user)"
            }
        }
    } else {
        print $"[ocm-sshd] WARNING: Default public key not found at ($default_pub_key)"
    }

    ^chmod 700 $ssh_dir
    if ($authorized_keys | path exists) {
        ^chmod 600 $authorized_keys
    } else {
        print $"[ocm-sshd] WARNING: authorized_keys not created for ($user), skipping chmod 600"
    }
    ^chown -R $"($user):($user)" $ssh_dir
}

def run-sshd [] {
    print "[ocm-sshd] Starting sshd..."
    let test_result = (^sshd -t | complete)
    if $test_result.exit_code != 0 {
        error make {msg: $"[ocm-sshd] sshd config check failed exit=($test_result.exit_code): ($test_result.stderr)"}
    }
    print "[ocm-sshd] sshd configuration valid"

    ^/usr/sbin/sshd
    print "[ocm-sshd] sshd started"
}

# Start sshd iff OCM_SSH_ENABLED=true and mode is server or client-and-server.
# Uses OCM_SSH_DEFAULT_USER, OCM_SSH_PORT, OCM_SSH_LISTEN. No-op otherwise.
export def start-sshd-if-enabled [] {
    let enabled = ($env.OCM_SSH_ENABLED? | default "false" | str downcase | str trim)
    if $enabled != "true" {
        print "[ocm-sshd] SSH server disabled (OCM_SSH_ENABLED != true)"
        return
    }

    let mode = ($env.OCM_SSH_MODE? | default "disabled" | str trim)
    if ($mode != "server") and ($mode != "client-and-server") {
        print $"[ocm-sshd] SSH server not needed mode=($mode)"
        return
    }

    let user = ($env.OCM_SSH_DEFAULT_USER? | default "root" | str trim)
    let port = ($env.OCM_SSH_PORT? | default "22" | str trim | into int)
    let listen = ($env.OCM_SSH_LISTEN? | default "0.0.0.0" | str trim)

    print $"[ocm-sshd] Configuring SSH server user=($user) port=($port) listen=($listen)..."

    generate-host-keys
    setup-sshd-config $port $listen $user
    setup-authorized-keys $user
    run-sshd

    print "[ocm-sshd] SSH server setup complete"
}
