#!/usr/bin/env nu

# SPDX-License-Identifier: AGPL-3.0-or-later
# DockyPody: container build scripts and images
# Copyright (C) 2025 Mahdi Baghbani <mahdi-baghbani@azadehafzar.io>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# SSH client environment setup for Kasm workspaces
# Generates ~/.ssh/config with Host patterns for peer containers

# Environment variables:
#   OCM_SSH_ENABLED       - "true" to enable SSH client setup
#   OCM_SSH_DEFAULT_USER  - SSH user for generated config (default: root)
#   OCM_SSH_PORT          - SSH port for generated config (default: 22)
#   OCM_SSH_PRIVATE_KEY   - Path to private key (default: derived from /opt/dockypody/ssh/ssh.json key_name, fallback: /opt/dockypody/ssh/dockypody)
#   OCM_SSH_KNOWN_HOSTS   - Path to known_hosts (default: /opt/dockypody/ssh/known_hosts)

def setup-ssh-directory [] {
    let ssh_dir = ($env.HOME | path join ".ssh")
    if not ($ssh_dir | path exists) {
        mkdir $ssh_dir
    }
    # Ensure correct permissions
    chmod 700 $ssh_dir
}

def copy-ssh-keys [
    private_key_src: string,
    public_key_src: string
] {
    let ssh_dir = ($env.HOME | path join ".ssh")
    let private_key_dest = ($ssh_dir | path join "id_ed25519")
    let public_key_dest = ($ssh_dir | path join "id_ed25519.pub")

    if ($private_key_src | path exists) {
        cp $private_key_src $private_key_dest
        chmod 600 $private_key_dest
        print $"[ocm-ssh-client-env] Copied private key to ($private_key_dest)"
    } else {
        print $"[ocm-ssh-client-env] WARNING: Private key not found at ($private_key_src)"
    }

    if ($public_key_src | path exists) {
        cp $public_key_src $public_key_dest
        chmod 644 $public_key_dest
        print $"[ocm-ssh-client-env] Copied public key to ($public_key_dest)"
    }
}

def copy-known-hosts [
    known_hosts_src: string
] {
    let ssh_dir = ($env.HOME | path join ".ssh")
    let known_hosts_dest = ($ssh_dir | path join "known_hosts")

    if ($known_hosts_src | path exists) {
        cp $known_hosts_src $known_hosts_dest
        chmod 644 $known_hosts_dest
        print $"[ocm-ssh-client-env] Copied known_hosts to ($known_hosts_dest)"
    } else {
        print $"[ocm-ssh-client-env] WARNING: known_hosts not found at ($known_hosts_src)"
    }
}

def generate-ssh-config [
    user: string,
    port: string
] {
    let ssh_dir = ($env.HOME | path join ".ssh")
    let config_file = ($ssh_dir | path join "config")

    let config_content = $"# Auto-generated by ocm-ssh-client-env.nu
# Do not edit manually - changes will be overwritten on container restart

Host *.docker
    User ($user)
    IdentityFile ~/.ssh/id_ed25519
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ~/.ssh/known_hosts
    Port ($port)

# Fallback for direct IP access
Host 172.*
    User ($user)
    IdentityFile ~/.ssh/id_ed25519
    StrictHostKeyChecking accept-new
    UserKnownHostsFile ~/.ssh/known_hosts
    Port ($port)
"

    $config_content | save -f $config_file
    chmod 600 $config_file
    print $"[ocm-ssh-client-env] Generated SSH config at ($config_file)"
}

def get-default-private-key [] {
    let ssh_json_path = "/opt/dockypody/ssh/ssh.json"
    let key_name = if ($ssh_json_path | path exists) {
        try {
            let meta = (open $ssh_json_path)
            $meta.key_name? | default "dockypody"
        } catch {
            "dockypody"
        }
    } else {
        "dockypody"
    }
    $"/opt/dockypody/ssh/($key_name)"
}

def main [] {
    let enabled = ($env.OCM_SSH_ENABLED? | default "false" | str downcase | str trim)
    if $enabled != "true" {
        print "[ocm-ssh-client-env] SSH client setup disabled (OCM_SSH_ENABLED != true)"
        return
    }

    let user = ($env.OCM_SSH_DEFAULT_USER? | default "root" | str trim)
    let port = ($env.OCM_SSH_PORT? | default "22" | str trim)
    let private_key = ($env.OCM_SSH_PRIVATE_KEY? | default (get-default-private-key) | str trim)
    let public_key = $"($private_key).pub"
    let known_hosts = ($env.OCM_SSH_KNOWN_HOSTS? | default "/opt/dockypody/ssh/known_hosts" | str trim)

    print $"[ocm-ssh-client-env] Setting up SSH client environment for user ($user)..."

    setup-ssh-directory
    copy-ssh-keys $private_key $public_key
    copy-known-hosts $known_hosts
    generate-ssh-config $user $port

    print "[ocm-ssh-client-env] SSH client setup complete."
    print "[ocm-ssh-client-env] Usage: ssh <service>.docker, for example: ssh nextcloud1.docker"
}
